local_backend: true
locale: 'de'

editor:
  preview: false

backend:
  name: github
  repo: paletti-festival/website
  branch: main

media_folder: "static"

collections:
- name: "dates"
  label: "Event"
  folder: "dates"
  create: true
  slug: "{{slug}}"
  fields:
    - {label: "Eventname", name: "title", widget: "string"}
    - {label: "Start", name: "date", widget: "datetime"}
    - {label: "Ende", name: "until", widget: "datetime"}
    - {label: "Status", name: "status", widget: "select", options: [{label: "Best채tigt", value: "CONFIRMED"}, {label: "Vorl채ufig", value: "TENTATIVE"}]}
    - {label: "Link f체r Schichten", name: "shift_url", widget: "string", required: false}
    - label: "Addresse"
      name: "place"
      widget: "object"
      fields: 
        - {label: "Bezeichnung", name: "name", widget: "string"}
        - {label: "Postadresse", name: "address", widget: "string"}
        - {label: "Koordinaten", name: "coordinates", widget: "string"}
        - label: "Kurzbeschreibung"
          name: "description"
          widget: "object"
          fields:
            - {label: "deutsch", name: "de", widget: "markdown"}
            - {label: "englisch", name: "en", widget: "markdown"}
    - label: "Programm"
      name: "program"
      widget: "object"
      fields: 
        - label: "Workshops"
          name: "workshops"
          widget: "list"
          fields:
            - {label: "Titel", name: "name", widget: "string"}
            - {label: "Start", name: "start", widget: "datetime"}
            - {label: "Ende", name: "end", widget: "datetime"}
            - {label: "Beschreibung", name: "description", widget: "markdown"}
        - label: "Vortr채ge"
          name: "presentations"
          widget: "list"
          fields:
            - {label: "Titel", name: "name", widget: "string"}
            - {label: "Start", name: "start", widget: "datetime"}
            - {label: "Ende", name: "end", widget: "datetime", required: false}
            - {label: "Beschreibung", name: "description", widget: "markdown"}
        - label: "Musik"
          name: "music"
          widget: "list"
          fields:
            - {label: "Titel", name: "name", widget: "string"}
            - {label: "Start", name: "start", widget: "datetime"}
            - {label: "Ende", name: "end", widget: "datetime", required: false}
            - {label: "Beschreibung", name: "description", widget: "markdown"}
- label: "Pages"
  name: "pages"
  files:
    - label: "Startseite"
      name: "home_de"
      file: "de/index.md"
      fields:
        - {widget: hidden, name: layout, default: index}
        - {label: Spruch unter paletti Schriftzug, name: description, widget: string}
        - {label: Haupttext, name: body, widget: markdown}
    - label: "Startseite (englisch)"
      name: "home_en"
      file: "en/index.md"
      fields:
        - {widget: hidden, name: layout, default: index}
        - {label: Spruch unter paletti Schriftzug, name: description, widget: string}
        - {label: Haupttext, name: body, widget: markdown}
    - label: "Impressum"
      name: "legal_de"
      file: "de/legal-notice.md"
      fields:
        - {widget: hidden, name: tags, default: footer}
        - {label: Titel, name: title, widget: string}
        - {label: Text, name: body, widget: markdown}
    - label: "Impressum (englisch)"
      name: "legal_en"
      file: "en/legal-notice.md"
      fields:
        - {widget: hidden, name: tags, default: footer}
        - {label: Titel, name: title, widget: string}
        - {label: Text, name: body, widget: markdown}
 
