name: 💾 Update Files
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 3 * * *'
jobs:
  download-form-style:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: apriljunge/download-upload
          ref: create-commit-only-on-filechange
          path: tmp
      - name: Install
        working-directory: tmp
        run: yarn
      - name: Build
        working-directory: tmp
        run: yarn build
      - uses: ./tmp/
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: https://sibforms.com/forms/end-form/build/sib-styles.css
          dir: styles
          filename: _sib-styles.css
  download-form-script:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: apriljunge/download-upload
          ref: create-commit-only-on-filechange
          path: tmp
      - name: Install
        working-directory: tmp
        run: yarn
      - name: Build
        working-directory: tmp
        run: yarn build
      - uses: ./tmp/
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: https://sibforms.com/forms/end-form/build/main.js
          dir: scripts
  download-form-script-license:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: apriljunge/download-upload
          ref: create-commit-only-on-filechange
          path: tmp
      - name: Install
        working-directory: tmp
        run: yarn
      - name: Build
        working-directory: tmp
        run: yarn build
      - uses: ./tmp/
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: https://sibforms.com/forms/end-form/build/main.js.LICENSE.txt
          dir: scripts
