name: Update File
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wow-actions/download-upload@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: https://sibforms.com/forms/end-form/build/sib-styles.css
          dir: styles
