name: 💾 Update Files
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 3 * * *'
permissions:
  contents: write
jobs:
  download-form-style:
    runs-on: ubuntu-latest
    env:
      FILE_URL: https://sibforms.com/forms/end-form/build/sib-styles.css
      TARGET_FILE: assets/styles/_sib-styles.css
      COMMIT_MESSAGE: "Update sib styles"
    steps:
      - uses: actions/checkout@v4

      - name: Download file
        run: |
          curl --fail --location --silent --show-error \
            --output "$TARGET_FILE" \
            "$FILE_URL"

      - name: Commit and push if changed
        run: |
          if git diff --quiet -- "$TARGET_FILE"; then
            echo "No changes."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add "$TARGET_FILE"
          git commit -m "$COMMIT_MESSAGE"
          git push
  download-form-script:
    runs-on: ubuntu-latest
    env:
      FILE_URL: https://sibforms.com/forms/end-form/build/main.js
      TARGET_FILE: scripts/main.js
      COMMIT_MESSAGE: "Update sib main.js"
    steps:
      - uses: actions/checkout@v4

      - name: Download file
        run: |
          curl --fail --location --silent --show-error \
            --output "$TARGET_FILE" \
            "$FILE_URL"

      - name: Commit and push if changed
        run: |
          if git diff --quiet -- "$TARGET_FILE"; then
            echo "No changes."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add "$TARGET_FILE"
          git commit -m "$COMMIT_MESSAGE"
          git push
  download-form-script-license:
    runs-on: ubuntu-latest
    env:
      FILE_URL: https://sibforms.com/forms/end-form/build/main.js.LICENSE.txt
      TARGET_FILE: scripts/main.js.LICENSE.txt
      COMMIT_MESSAGE: "Update sib main.js.LICENSE.txt"
    steps:
      - uses: actions/checkout@v4

      - name: Download file
        run: |
          curl --fail --location --silent --show-error \
            --output "$TARGET_FILE" \
            "$FILE_URL"

      - name: Commit and push if changed
        run: |
          if git diff --quiet -- "$TARGET_FILE"; then
            echo "No changes."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add "$TARGET_FILE"
          git commit -m "$COMMIT_MESSAGE"
          git push
