on:
  workflow_dispatch:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-24.04
    steps:
    - name: ⏰ Set timezone
      uses: szenius/set-timezone@v2.0
      with:
        timezoneLinux: "Europe/Berlin"
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 21
      uses: actions/setup-node@v4
      with:
        node-version: '21.3'
      
    - name: 🔨 Build Project
      run: |
        yarn install --frozen-lockfile
        yarn run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.server }}
        username: ${{ secrets.user }}
        password: ${{ secrets.password }}
        local-dir: ./_site/
        server-dir: /httpdocs/
